### ISSUE TITLE
error on wdgrl

### ISSUE THREAD

**Issue by Dr-Zhou** [jvanvugt/pytorch-domain-adaptation#2]
![image](https://user-images.githubusercontent.com/26479520/64510994-eb7b2180-d315-11e9-8308-d29cb3d1023c.png)

**Comment by shijianjian** [comment]
It is not an error on this repo. It is on your Dataset class.

**Comment by Dr-Zhou** [comment]
> It is not an error on this repo. It is on your Dataset class.

but I use it in this repo。and I don't change anything.

**Comment by jvanvugt** [comment]
Judging by the error, it seems you did not follow step 1 of the instructions in the README correctly

**Comment by Dr-Zhou** [comment]
change dataset path.I did it.

**Comment by xiangchen2011** [comment]
I met the same error.
```python
File "mtrand.pyx", line 896, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken
```

**Comment by gmberton** [comment]
I had the same problem... the path of DATA_DIR in config.py should point to the folder with the BSR directory, not to its parent directory. It would be nice to have a check in BSDS500 in data.py, something like 
if not os.path.exists(image_folder): raise FileNotFound(image_folder + " does not exist, change the DATA_DIR variable!")

**Comment by Learn2Ln** [comment]
Download the BSDS500 dataset and extract it at the right folder, this error will not happen.
